export const language = {
  eng: {
    months: [
      "January",
      "February",
      "March",
      "April",
      "May",
      "June",
      "July",
      "August",
      "September",
      "October",
      "November",
      "December",
    ],
    month_subs: [
      "Jan",
      "Feb",
      "Apr",
      "Mar",
      "June",
      "July",
      "Aug",
      "Sept",
      "Oct",
      "Nov",
      "Dec",
    ],
    weeks: [
      "Sunday",
      "Monday",
      "Tuesday",
      "Wednesday",
      "Thursday",
      "Friday",
      "Saturday",
    ],
    week_subs: ["SU", "MO", "TU", "WE", "TH", "FR", "SA"],
  },
  ita: {
    months: [
      "Gennaio",
      "Febbraio",
      "MArzo",
      "Aprile",
      "Maggio",
      "Giugno",
      "Luglio",
      "Agosto",
      "Settembre",
      "Ottobre",
      "Novembre",
      "Dicembre",
    ],
    month_subs: [
      "Gen",
      "Feb",
      "Apr",
      "Mar",
      "Giu",
      "Lug",
      "Ago",
      "Set",
      "Ott",
      "Nov",
      "Dic",
    ],
    weeks: [
      "Domenica",
      "Lunedì",
      "Martedì",
      "Mercoledì",
      "Giovedì",
      "Venerdì",
      "Sabato",
    ],
    week_subs: ["DOM", "LUN", "MAR", "MER", "GIO", "VEN", "SAB"],
  },
};
